# Generated by Django 3.2.5 on 2021-07-24 19:16

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('myhood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_image',
            field=cloudinary.models.CloudinaryField(default='Image', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_service',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='neighborhood_image',
            field=cloudinary.models.CloudinaryField(default='Image', max_length=255, verbose_name='image'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', tinymce.models.HTMLField()),
                ('posted_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('neighborhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhood.neighborhood')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhood.user')),
            ],
        ),
    ]
