# Generated by Django 3.2.5 on 2021-07-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhood', '0003_remove_business_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
    ]
