# Generated by Django 3.2.5 on 2021-07-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhood', '0009_business_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='occupants_count',
        ),
    ]
