# Generated by Django 3.2.5 on 2021-07-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhood', '0010_remove_neighborhood_occupants_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_name',
            field=models.EmailField(max_length=30),
        ),
    ]
